sudo: required
language: python
python:
  - "3.5"
  - "3.6"
script:
  - python setup.py install
  - pytest -vs tests

before_install:
  - pip install pandas synapseclient

# matrix:
#   include:
#     - os: linux
#       python: 3.5.3
#     - os: linux
#       python: 3.6.2